### ISSUE TITLE
ImportError: cannot import name six

### ISSUE THREAD

**Issue by nop33** [andrewschoen/django-cms-demo#8]
Following your instructions, I got the following error message after executing 

```
$ python manage.py syncdb --all
```

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/src/filer/filer/models/__init__.py", line 2, in <module>
    from filer.models.clipboardmodels import *
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/src/filer/filer/models/clipboardmodels.py", line 7, in <module>
    from filer.models import filemodels
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/src/filer/filer/models/filemodels.py", line 9, in <module>
    from filer.fields.multistorage_file import MultiStorageFileField
  File "/Users/my-name/dev/python/django-cms_demo/django-cms-demo/django-cms-demo/env/src/filer/filer/fields/multistorage_file.py", line 7, in <module>
    from django.utils import six

```

**Comment by mostafahasseib** [comment]
it work  with python 3
